version: '3'
services:
  app:
    container_name: teste-app
    build: .
    command: npm run dev
    ports:
      - "8088:8088"
    depends_on:
      - db
    networks:
      - my-network
    

  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - my-network
    container_name: teste-db

networks:
  my-network: